[package]
name = "server"
version = "0.1.0"
authors = ["Sam <tritoke@protonmail.com>"]
edition = "2021"

[dependencies]
cortex-m = "0.7"
embedded-hal = "0.2"
teensy4-panic = "0.2"
teensy4-bsp = { version = "0.4", features = [ "rt" ] }
usb-device = "0.2.9"
usbd-serial = "0.1.1"
